package Frame;

import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import DataAccess.CategoryRepository;
import DataAccess.NewsletterRepository;
import DataAccess.SectionRepository;
import Entity.Category;
import Entity.Newsletter;
import Entity.Section;

public class CreateSectionJDialog extends javax.swing.JDialog {
	SectionRepository secRepo;
    /**
     * Creates new form CadastraSecoesJDialog
     */
    public CreateSectionJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        secRepo = new SectionRepository(Main.App.db);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulojLabel = new javax.swing.JLabel();
        conteudojLabel = new javax.swing.JLabel();
        categoriajComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        newsletterjLabel = new javax.swing.JLabel();
        newsletterjComboBox = new javax.swing.JComboBox();
        titulojTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        conteudojTextPane = new javax.swing.JTextPane();
        savejButton = new javax.swing.JButton();
        sairjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titulojLabel.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        titulojLabel.setText("Titulo:");

        conteudojLabel.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        conteudojLabel.setText("Conteudo:");

        categoriajComboBox.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        categoriajComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        try {
        	CategoryRepository catRepo = new CategoryRepository(Main.App.db);
        	ResultSet catRs = catRepo.findAll();
        	while (catRs.next()) {
        		Category category = new Category();
        		category.setDescription(catRs.getString("description"));
        		category.setId(catRs.getInt("id"));
        		category.setTitle(catRs.getString("title"));
        		categoriajComboBox.addItem(category);
        	}
        } catch (SQLException ex) {
        	ex.printStackTrace();
        }

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel1.setText("Categoria:");

        newsletterjLabel.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        newsletterjLabel.setText("Newsletter:");

        newsletterjComboBox.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        newsletterjComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        try {
        	NewsletterRepository newsRepo = new NewsletterRepository(Main.App.db);
        	ResultSet newsRs = newsRepo.findAll();
        	while (newsRs.next()) {
        		Newsletter newsletter = new Newsletter();
        		newsletter.setDate(newsRs.getDate("date"));
        		newsletter.setId(newsRs.getInt("id"));
        		newsletter.setEnabled(newsRs.getBoolean("enabled"));
        		newsletterjComboBox.addItem(newsletter);
        	}
        } catch (SQLException ex) {
        	ex.printStackTrace();
        }

        jScrollPane1.setViewportView(conteudojTextPane);

        savejButton.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        savejButton.setText("Salvar");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				saveActionPerformed(e);
			}
        });

        sairjButton.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        sairjButton.setText("Sair");
        sairjButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(newsletterjLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(categoriajComboBox, 0, 135, Short.MAX_VALUE)
                                .addComponent(newsletterjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(savejButton)
                                .addGap(44, 44, 44)
                                .addComponent(sairjButton)))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conteudojLabel)
                            .addComponent(titulojLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulojLabel)
                    .addComponent(titulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conteudojLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newsletterjLabel)
                    .addComponent(newsletterjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savejButton)
                    .addComponent(sairjButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_sairjButtonActionPerformed
    
    private void saveActionPerformed(java.awt.event.ActionEvent e) {
    	try {
    		Section section = new Section();
        	section.setCategory((Category) categoriajComboBox.getSelectedItem());
        	section.setNewsletter((Newsletter) newsletterjComboBox.getSelectedItem());
        	section.setTitle(titulojTextField.getText());
        	section.setContent(conteudojTextPane.getText());
        	
        	secRepo.insert(section);
        	JOptionPane.showMessageDialog(null, "Seção inserida com sucesso");
        	dispose();
    	} catch (SQLException ex) {
    		System.out.println("Não foi possivel inserir seção");
    		ex.printStackTrace();
    	}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateSectionJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateSectionJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateSectionJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateSectionJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
			public void run() {
                CreateSectionJDialog dialog = new CreateSectionJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox categoriajComboBox;
    private javax.swing.JLabel conteudojLabel;
    private javax.swing.JTextPane conteudojTextPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox newsletterjComboBox;
    private javax.swing.JLabel newsletterjLabel;
    private javax.swing.JButton sairjButton;
    private javax.swing.JButton savejButton;
    private javax.swing.JLabel titulojLabel;
    private javax.swing.JTextField titulojTextField;
    // End of variables declaration//GEN-END:variables
}
