package Frame;

import java.awt.event.ActionEvent;

import javax.swing.JLabel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;

import java.awt.Color;

import javax.swing.LayoutStyle.ComponentPlacement;

import java.awt.event.ActionListener;

public class RegistrationJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CadastrosJFrame
     */
    public RegistrationJFrame() {
    	getContentPane().setBackground(new Color(238, 238, 238));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        cadastrarUsuariosjButton = new javax.swing.JButton();
        
                cadastrarUsuariosjButton.setText("Usuários");
                cadastrarUsuariosjButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				cadastrarUsuariosActionPerformed(e);
			}
                });
                
                        cadastrarNewsletterjButton = new javax.swing.JButton();
                        
                                cadastrarNewsletterjButton.setText("Newsletter");
                                cadastrarNewsletterjButton.addActionListener(new java.awt.event.ActionListener() {
                                    @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        cadastrarNewsletterjButtonActionPerformed(evt);
                                    }
                                });
                                cadastrarGruposjButton = new javax.swing.JButton();
                                
                                        cadastrarGruposjButton.setText("Grupos");
                                        cadastrarGruposjButton.addActionListener(new java.awt.event.ActionListener() {
                                        	@Override
                                        	public void actionPerformed(java.awt.event.ActionEvent e) {
                                        		cadastrarGrupojButtonActionPerformed(e);
                                        	}
                                        });
                                        cadastrarCategoriasjButton = new javax.swing.JButton();
                                        
                                                cadastrarCategoriasjButton.setText("Categorias");
                                                cadastrarCategoriasjButton.addActionListener(new java.awt.event.ActionListener() {
                                                	@Override
                                                	public void actionPerformed(java.awt.event.ActionEvent e) {
                                                		cadastrarCategoriasjButtonActionPerformed(e);
                                                	}
                                                });
                                                sairjButton = new javax.swing.JButton();
                                                
                                                        sairjButton.setText("SAIR");
                                                        sairjButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				sairjButtonActionPerformed(e);
			}
                                                        });
                                                        cadastrarAssinantesjButton = new javax.swing.JButton();
                                                        
                                                                cadastrarAssinantesjButton.setText(" Assinantes");
                                                                cadastrarAssinantesjButton.addActionListener(new java.awt.event.ActionListener() {
                                                                    @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                                        cadastrarAssinantesjButtonActionPerformed(evt);
                                                                    }
                                                                });
                                                        
                                                        label = new JLabel("");
                                        cadastrarSecoesjButton = new javax.swing.JButton();
                                        cadastrarSecoesjButton.addActionListener(new ActionListener() {
                                        	public void actionPerformed(ActionEvent e) {
                                        		cadastrarSecoesActionPerformed(e);
                                        	}
                                        });
                                        
                                                cadastrarSecoesjButton.setText("Seções");
                GroupLayout groupLayout = new GroupLayout(getContentPane());
                groupLayout.setHorizontalGroup(
                	groupLayout.createParallelGroup(Alignment.LEADING)
                		.addGroup(groupLayout.createSequentialGroup()
                			.addContainerGap()
                			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                				.addGroup(groupLayout.createSequentialGroup()
                					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                						.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
                							.addComponent(label)
                							.addGap(88))
                						.addGroup(groupLayout.createSequentialGroup()
                							.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING, false)
                								.addComponent(cadastrarAssinantesjButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                								.addComponent(cadastrarCategoriasjButton, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                							.addPreferredGap(ComponentPlacement.RELATED)))
                					.addGap(18)
                					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                						.addComponent(cadastrarGruposjButton, GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                						.addComponent(cadastrarNewsletterjButton, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE))
                					.addPreferredGap(ComponentPlacement.RELATED)
                					.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
                						.addComponent(cadastrarUsuariosjButton, GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                						.addComponent(cadastrarSecoesjButton, GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                					.addContainerGap())
                				.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
                					.addComponent(sairjButton, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE)
                					.addGap(253))))
                );
                groupLayout.setVerticalGroup(
                	groupLayout.createParallelGroup(Alignment.LEADING)
                		.addGroup(groupLayout.createSequentialGroup()
                			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                				.addGroup(groupLayout.createSequentialGroup()
                					.addContainerGap()
                					.addComponent(cadastrarSecoesjButton, GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                				.addGroup(groupLayout.createSequentialGroup()
                					.addGap(6)
                					.addComponent(label)
                					.addPreferredGap(ComponentPlacement.RELATED)
                					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                						.addComponent(cadastrarGruposjButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                						.addComponent(cadastrarAssinantesjButton, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE))))
                			.addPreferredGap(ComponentPlacement.RELATED)
                			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
                				.addComponent(cadastrarUsuariosjButton, GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                				.addComponent(cadastrarCategoriasjButton, GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                				.addComponent(cadastrarNewsletterjButton, GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                			.addGap(129)
                			.addComponent(sairjButton, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
                			.addGap(21))
                );
                getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarNewsletterjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarNewsletterjButtonActionPerformed
    	CreateNewsletterJDialog newsletterFrame = new CreateNewsletterJDialog(this, true);
    	newsletterFrame.setVisible(true);
    }//GEN-LAST:event_cadastrarNewsletterjButtonActionPerformed

    private void cadastrarAssinantesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAssinantesjButtonActionPerformed
        SignSubscriberJDialog subsFrame = new SignSubscriberJDialog(this, true);
        subsFrame.setVisible(true);
    }//GEN-LAST:event_cadastrarAssinantesjButtonActionPerformed

    private void cadastrarCategoriasjButtonActionPerformed(java.awt.event.ActionEvent e) {
    	CreateCategoriasJDialog catFrame = new CreateCategoriasJDialog(this, true);
    	catFrame.setVisible(true);
    }
    
    private void sairjButtonActionPerformed(java.awt.event.ActionEvent e) {
    	this.dispose();
    }
    
    private void cadastrarGrupojButtonActionPerformed(java.awt.event.ActionEvent e) {
    	CreateGroupJDialog groupFrame = new CreateGroupJDialog(this, true);
    	groupFrame.setVisible(true);
    }
    
    private void cadastrarUsuariosActionPerformed(java.awt.event.ActionEvent e) {
    	SignUser userFrame = new SignUser(this, true);
		userFrame.setVisible(true);
    }
    
    private void cadastrarSecoesActionPerformed(java.awt.event.ActionEvent e) {
    	CreateSectionJDialog sectionFrame = new CreateSectionJDialog(this, true);
    	sectionFrame.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
			public void run() {
                new RegistrationJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarAssinantesjButton;
    private javax.swing.JButton cadastrarCategoriasjButton;
    private javax.swing.JButton cadastrarGruposjButton;
    private javax.swing.JButton cadastrarNewsletterjButton;
    private javax.swing.JButton cadastrarSecoesjButton;
    private javax.swing.JButton cadastrarUsuariosjButton;
    private javax.swing.JButton sairjButton;
    private JLabel label;
    // End of variables declaration//GEN-END:variables
}
