package Frame;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

import DataAccess.GroupRepository;
import DataAccess.SubscriberRepository;
import Entity.Group;
import Entity.Subscriber;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;

public class SignSubscriberJDialog extends javax.swing.JDialog {
	protected SubscriberRepository subsRepo;
	protected GroupRepository groupRepo;

    /**
     * Creates new form CadastraAssinanteJDialog
     */
    public SignSubscriberJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Connection db = Main.App.db;
        this.subsRepo = new SubscriberRepository(db);
        //this.groupRepo = new GroupRepository(db);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sairjButton = new javax.swing.JButton();
        grupojLabel = new javax.swing.JLabel();
        grupojComboBox = new javax.swing.JComboBox();
        savejButton = new javax.swing.JButton();
        emailjLabel = new javax.swing.JLabel();
        emailjTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        sairjButton.setText("Sair");
        sairjButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjButtonActionPerformed(evt);
            }
        });

        grupojLabel.setText("Grupo:");
        
        grupojComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        try {
        	groupRepo = new GroupRepository(Main.App.db);
			ResultSet groupsRs = groupRepo.findAll();
			while (groupsRs.next()) {
				Group group = new Group();
				group.setId(groupsRs.getInt("id"));
				group.setName(groupsRs.getString("name"));
				grupojComboBox.addItem(group);
			}
		} catch (SQLException ex) {
			ex.printStackTrace();
		}

        savejButton.setText("Salvar");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent e) {
                savejButtonActionPerformed(e);
            }
        });

        emailjLabel.setText("Email:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(grupojLabel)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(grupojComboBox, 0, 95, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(110)
        					.addComponent(savejButton)
        					.addGap(37)
        					.addComponent(sairjButton))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(emailjLabel)
        					.addGap(18)
        					.addComponent(emailjTextField, GroupLayout.PREFERRED_SIZE, 326, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(emailjLabel)
        				.addComponent(emailjTextField, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        			.addGap(55)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(grupojLabel)
        				.addComponent(grupojComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(savejButton)
        				.addComponent(sairjButton)))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjButtonActionPerformed
        dispose();
    }//GEN-LAST:event_sairjButtonActionPerformed
    
    private void savejButtonActionPerformed(java.awt.event.ActionEvent e) {
    	try {
    		Subscriber subs = new Subscriber();
        	subs.setEmail(emailjTextField.getText());
        	subs.setGroup((Group) grupojComboBox.getSelectedItem());
			subsRepo.insert(subs);
			JOptionPane.showMessageDialog(null, "Assinante cadastrado com sucesso");
			this.dispose();
		} catch (SQLException ex) {
			System.out.println("Não foi possível cadastrar assinante");
			ex.printStackTrace();
		}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignSubscriberJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignSubscriberJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignSubscriberJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignSubscriberJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
			public void run() {
                SignSubscriberJDialog dialog = new SignSubscriberJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JComboBox grupojComboBox;
    private javax.swing.JLabel grupojLabel;
    private javax.swing.JButton sairjButton;
    private javax.swing.JButton savejButton;
    // End of variables declaration//GEN-END:variables
}
